### ISSUE TITLE
Add .gitignore

### ISSUE THREAD

**Issue by RohanSakhale** [archanpatkar/Tachyon#1]
It is always a good practice to commit code of what you have contributed yourself and not commit what is generated by system/compilers and also do not commit from third-party libraries

Refer to the Global gitignore template to best suit you from https://gitignore.io

### Recommended

https://www.gitignore.io/api/java%2Cpython%2Ckotlin

**Comment by archanpatkar** [comment]
I usually create **gitignore** when there are _external dependancies_ and the **Kotlin code** here is completely generated by me. There are no _external_ _source-code libraries_ used. I am removing the **bin** folder and the **jar** file. I've also added **gitignore**.
